### ISSUE TITLE
send cycles to tipjar 

### ISSUE THREAD

**Issue by letmejustputthishere** [ninegua/tipjar#4]
currently afaik it's only possible to send ICP that are then converted to cycles. i bought a bunch of XTC on sonic, bc it's cheaper than burning ICP atm and would love to send them to tipjar. is there a work around or can this feature be added?

**Comment by ninegua** [comment]
This will require a new feature. For example, we could add the following method to tipjar:

```
service {
  ...
  deposit(principal) -> ();
}
```

It can deposit all cycles sent along this method to the account under the given principal. Apparently it will require the caller to be a canister that can send cycles with a call. A developer can then use the following command to make this call:

```
dfx canister --wallet=... call --with-cycles=... tipjar deposit ...`
```

Is this sufficient for your need? Alternatively we could think of a UI flow to add support for XTC, but depending on which XTC, and how it can integrate with the current UI flow, it becomes a more involved effort.

**Comment by letmejustputthishere** [comment]
This is perfect!

**Comment by letmejustputthishere** [comment]
The dfx flow is good enough for me :)

**Comment by ninegua** [comment]
@letmejustputthishere can you have a look at #6 and see if it is good enough for your use?

It has been deployed so you can give it a try already
